/*
 * Build configuration.
 *
 * Adapted from obsidian-sample-plugin (https://github.com/obsidianmd/obsidian-sample-plugin),
 * copyright the Obsidian team, MIT licensed. The banner text and the list of externals
 * are taken from that template; the vault-output and asset-copying behaviour below is
 * specific to this project.
 */
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { existsSync, mkdirSync, copyFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// In dev, build straight into the vault so Obsidian picks up changes on reload.
// DevVault lives in iCloud, so this also syncs the plugin to Obsidian on iOS.
const devVaultPlugin =
	process.env.OBSIDIAN_PLUGIN_DIR ??
	join(
		homedir(),
		"Library/Mobile Documents/iCloud~md~obsidian/Documents/DevVault/.obsidian/plugins/quotable"
	);

const outDir = prod ? "." : devVaultPlugin;

if (!prod) {
	mkdirSync(outDir, { recursive: true });
}

/** Copy manifest.json and styles.css next to the bundle so the vault copy is complete. */
const copyStaticAssets = {
	name: "copy-static-assets",
	setup(build) {
		build.onEnd(() => {
			if (prod) return;
			for (const file of ["manifest.json", "styles.css"]) {
				if (existsSync(file)) copyFileSync(file, join(outDir, file));
			}
			console.log(`[quotable] built -> ${outDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: join(outDir, "main.js"),
	minify: prod,
	plugins: [copyStaticAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
